SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.BOOK_TOTAL_SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID JOIN
(SELECT BOOK_ID, SUM(SALES) BOOK_TOTAL_SALES FROM BOOK_SALES 
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY BOOK_ID) BS
ON B.BOOK_ID = BS.BOOK_ID
group by B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
order by b.AUTHOR_ID, b.CATEGORY desc