SELECT H.HISTORY_ID, 
(H.END_DATE - H.START_DATE + 1) * C.DAILY_FEE * NVL((100 - P.DISCOUNT_RATE)/100, 1) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN
CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
LEFT OUTER JOIN
CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
AND P.DURATION_TYPE = (
    CASE WHEN (H.END_DATE - H.START_DATE + 1) >= 90 THEN '90일 이상'
        WHEN (H.END_DATE - H.START_DATE + 1) >= 30 THEN '30일 이상'
        WHEN (H.END_DATE - H.START_DATE + 1) >= 7 THEN '7일 이상'
        ELSE NULL END
)
WHERE 1 = 1
    AND C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC